version: 2.1

jobs:
  one:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - setup_remote_docker
    - run: echo "A first hello"
    - restore_cache:
        keys:
          - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
    
    - run:
        name: Restoring dependencies into docker volumes
        command: |
          NAME=dependencies
          CACHE_PATH=deps
          set -x
          mkdir -p $CACHE_PATH
          docker-compose -f docker-compose.yml -f circle-dockup.yml up --no-start $NAME
          docker cp $CACHE_PATH/. $NAME:/backup
          docker-compose -f docker-compose.yml -f circle-dockup.yml up --no-recreate $NAME
          docker rm -f $NAME
    
    # - run:
    #     name: Backing up dependencies from docker volumes
    #     command: |
    #       NAME=dependencies
    #       CACHE_PATH=/usr/local/lib/python3.8/site-packages
    #       set -x
    #       docker-compose -f docker-compose.yml -f circle-dockup.yml run --name $NAME $NAME backup
    #       docker cp $NAME:/backup/. $CACHE_PATH
    #       docker rm -f $NAME
    
    - save_cache:
        key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
          - deps

    - run: >
        docker build
        .
  two:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - setup_remote_docker
    - run: echo "A first hello"
    

workflows:
  version: 2
  one_and_two:
    jobs:
    - one
    - two
    