version: 2.1

jobs:
  one:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        keys:
          - deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}

    - run: docker build -t payers1/test-container .
    - run: docker run --name app payers1/test-container /bin/true
    - run: docker cp app:/usr/local/lib/python3.8/site-packages /usr/local/lib/python3.8/site-packages
    - run: docker run app flask --help 
    - save_cache:
        key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
          - /usr/local/lib/python3.8/site-packages


workflows:
  version: 2
  one_and_two:
    jobs:
    - one
    